name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\cs
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
    - name: Build
      run: dotnet build .\shim.sln
    - name: Test
      run: dotnet test .\test\test.csproj
